import Head from 'next/head'
import Image from 'next/image'
import { Fotos } from '../components/fotos'
import Galeria from '../components/galeria'
import Hero from '../components/hero'
import Instagram from '../components/instagram'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Eme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Galeria  fotos={Fotos}/>
      
    </div>
  )
}
